connectedin/urls.py
from django.contrib import admin
from django.urls import path
from perfis.views import exibir_perfil, convidar, aceitar, perfil, recusar, desfazer
from posts.views import timeline
from usuario.views import RegistrarUsuarioView
from django.contrib.auth import views as v

urlpatterns = [
    path('',timeline, name='timeline'),
    
    path('admin/', admin.site.urls),
    path('perfil/', perfil ,name='my_perfil'),
    path('perfil/<int:perfil_id>', exibir_perfil, name='exibir'),
    path('perfil/<int:perfil_id>/convidar',convidar, name='convidar'),
    path('convite/<int:convite_id>/aceitar',aceitar, name='aceitar'),
    path('convite/<int:convite_id>/recusar',recusar, name='recusar'),
    path('perfil/<int:perfil_id>/desfazer',desfazer, name='desfazer'),

    

    path('registrar/', RegistrarUsuarioView.as_view(), name='registrar'),
    path('login/', v.LoginView.as_view(template_name='login.html'), name='login'),  
    path('logout/', v.LogoutView.as_view(template_name='login.html'), name='logout'),
]

perfis/models.py
from django.db import models
from django.contrib.auth.models import User


class Perfil(models.Model):
    nome = models.CharField(max_length=255, null=False)
    telefone = models.CharField(max_length=20, null= False)
    nome_empresa = models.CharField(max_length=255, null=False)
    contatos = models.ManyToManyField('Perfil')
    usuario = models.OneToOneField(User, null=True ,related_name="perfil", on_delete= models.CASCADE)
    
    
    @property
    def email(self):
        return self.usuario.email

    def __str__(self):
        return self.nome

    def convite_a_si_mesmo(self, perfil):
        return self == perfil

    
    def desfazer(self, perfil):
        self.contatos.remove(perfil)
        perfil.contatos.remove(self)

    def pode_convidar(self, perfil):
        nao_pode = self.convite_a_si_mesmo(perfil) or self.ja_eh_contato(perfil) or self.ja_possui_convite(perfil)
        return not nao_pode

    def ja_eh_contato(self, perfil):
        return self.contatos.filter(id = perfil.id).exists()

    def ja_possui_convite(self, perfil):               
        return (Convite.objects.filter(solicitante = self, convidado = perfil).exists() or
                Convite.objects.filter(solicitante = perfil, convidado = self).exists()   )

    def convidar(self, perfil_convidado):
        if self.pode_convidar(perfil_convidado):
            convite = Convite(solicitante=self,convidado = perfil_convidado)
            convite.save()


class Convite(models.Model):
    solicitante = models.ForeignKey(Perfil,on_delete=models.CASCADE,related_name='convites_feitos' )
    convidado = models.ForeignKey(Perfil, on_delete= models.CASCADE, related_name='convites_recebidos')

    def aceitar(self):        
        self.solicitante.contatos.add(self.convidado)
        self.convidado.contatos.add(self.solicitante)
        self.delete()
    
    
    def recusar(self):        
        self.delete()

posts/models.py
from django.db import models
from perfis.models import Perfil

class Postagem(models.Model):
    texto = models.CharField(max_length=255, null=False)
    data_postagem = models.DateTimeField(auto_now_add=True, blank=True)
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE, related_name='Postagens')
    
    def __str__(self):
        return self.texto

usuario/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django.forms import ModelForm
from posts.models import Postagem


class PostagemForm(ModelForm):
    class Meta:
        model = Postagem
        fields = ['texto']

usuario/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa =forms.CharField(required=True)
    
    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Por Favor, Verifique os dados informados')
            valid = False
        user_exists = User.objects.filter(username=self.cleaned_data['nome']).exists()
        if user_exists:
            self.adiciona_erro('Usuário já Cadastrado ')
            valid = False

        
        return valid

    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, 
                                         forms.utils.ErrorList())
        errors.append(message)

perfis/views.py
from django.shortcuts import render
from perfis.models import Perfil, Convite
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def perfil(request):
	return render(request, 'index.html',{'perfis' : Perfil.objects.all(),
										 'perfil_logado' : get_perfil_logado(request)})

@login_required
def exibir_perfil(request, perfil_id):

	perfil = Perfil.objects.get(id=perfil_id)

	return render(request, 'perfil.html',
		          {'perfil' : perfil, 
				   'perfil_logado' : get_perfil_logado(request)})

@login_required
def convidar(request,perfil_id):
	perfil_a_convidar = Perfil.objects.get(id=perfil_id)
	perfil_logado = get_perfil_logado(request)
	
	if(perfil_logado.pode_convidar(perfil_a_convidar)):
		perfil_logado.convidar(perfil_a_convidar)
	
	return  redirect('/perfil/') 

@login_required
def get_perfil_logado(request):
	return request.user.perfil

@login_required
def aceitar(request, convite_id):
	convite = Convite.objects.get(id = convite_id)
	convite.aceitar()
	return redirect('/perfil')

@login_required
def recusar(request, convite_id):
	convite = Convite.objects.get(id = convite_id)
	convite.recusar()
	return redirect('/perfil/')

@login_required
def desfazer(request, perfil_id):
	perfil = Perfil.objects.get(id=perfil_id)
	perfil.desfazer(get_perfil_logado(request))
	return redirect('/perfil/')

posts/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from perfis.views import get_perfil_logado
from posts.models import Postagem 
from posts.forms import PostagemForm 
from django.contrib.auth.decorators import login_required


@login_required
def timeline(request):
    template_name='timeline.html'
    user = get_perfil_logado(request)
    form = PostagemForm()
    friends = user.contatos.all()
    postagens = Postagem.objects.filter(perfil__in=friends) | Postagem.objects.filter(perfil= user)
    postagens.order_by('data_postagem').reverse()
    context = {'perfil_logado': user,'form':form, 'posts':postagens}
    if request.method=='POST':
        form = PostagemForm(request.POST)
        if form.is_valid():
            data_form = form.cleaned_data
            post = Postagem(texto=data_form['texto'], perfil=context['perfil_logado'])
            post.save()
            return redirect('/')
    return render(request, template_name, context)

usuario/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.contrib.auth.models import User
from perfis.models import Perfil
from usuario.forms import RegistrarUsuarioForm

class RegistrarUsuarioView(View):
    template_name = 'registrar.html'
    
    
    def get(self, request):
        return render(request, self.template_name)


    def post(self, request):
        form = RegistrarUsuarioForm(request.POST)
        if form.is_valid():
            dados_form = form.cleaned_data
            usuario = User.objects.create_user(username = dados_form['nome'],
                                               email = dados_form['email'],
                                               password = dados_form['senha'] )
            perfil = Perfil(nome = dados_form['nome'], telefone=dados_form['telefone'],
                                nome_empresa=dados_form['nome_empresa'], usuario=usuario)
            perfil.save()
            return redirect('/login')
        return render(request, self.template_name, {'form':form})

perfis/templates/base.html
{% load static %}
<!doctype html>
<html lang = "pt-br">
	<head>
		<meta charset="utf-8">
		<title>
			{% block title %}
        	{% endblock %}
		</title>
		<link rel="stylesheet" 
			 href="{% static 'styles/bootstrap.css' %}">
		<link rel="stylesheet" 
			 href="{% static 'styles/main.css' %}">
		 
		<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->

	</head>
	<body>
		<div class="container">
			<div class = "header">
				<ul class = "nav nav-pills pull-right">
					<li><a href = "{% url 'my_perfil' %}">{{ perfil_logado.nome }}</a></li>
					<li><a href = "{% url 'logout'%}">Logout</a></li>
				</ul>
				<h3 class = "text-muted"> 
					<a href="{% url 'timeline' %}">
						ConnectedIn
					</a>
				</h3>
			</div>
			
			<div class="row content">
				{% block body%}
				{% endblock %}				
			</div>		
		</div>	
	</body>
</html>

perfis/templates/index.html
{% extends 'base.html' %}
{% block title %}
    {{ perfil_logado.nome }}
{% endblock %}



{% block body %}
<div class="col-lg-12"> 		
	<div class="panel panel-default">
		<div class="panel-heading">
			<strong>Todos os perfis</strong>
		</div>
		{% if perfis %}
		<ul class="list-group">
			{% for perfil in perfis %}
				<li class="list-group-item">
					<a href = "{% url 'exibir' perfil.id %}">	{{ perfil.nome }} / {{ perfil.email }}
					</a>	
				</li>
			{% endfor %}
		{% else %}	
			<p>Não há perfis cadastrados</p>
		{% endif %}
		</ul>
	</div>	

    <div class="panel panel-default">
        {% with total=perfil_logado.contatos.count %}
            {% if total %}
                <div class="panel-heading">
                    <strong> {{ total }}  
                        Contato{{ total|pluralize }}
                    </strong>
                </div>
                <ul class="list-group">
                    {% for perfil in perfil_logado.contatos.all %}
                        <li class = "list-group-item">
                            <a href = "{% url 'exibir' perfil.id %}">
                                {{ perfil }}
                            </a>
                            <a class="pull-right" href="{% url 'desfazer' perfil.id %}">
                                desfazer amizade
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="panel-body">
                    Não há contatos :(
                </div>    
            {% endif %}
        {% endwith %}    
    </div>    

    <div class="panel panel-default">
        {% with total=perfil_logado.convites_recebidos.count %}

            {% if total %}
                <div class="panel-heading">
                    <strong> {{ total }}  
                    Convite{{ total|pluralize }} aguardando aprovação</strong>
                </div>
                <ul class="list-group">
                    {% for convite in perfil_logado.convites_recebidos.all %}
                        <li class = "list-group-item">
                           <ul class = "list-inline">
                                <li class = "list-inline-item">
                                    <a href = "{% url 'exibir' convite.solicitante.id %}">
                                        {{convite.solicitante.nome}}
                                    </a>
                                </li>
                                <li class = "list-inline-item pull-right">
                                    <a href = "{% url 'recusar' convite.id %}">recusar</a>
                                </li>
                                <li class = "list-inline-item pull-right">
                                    <a href = "{% url 'aceitar' convite.id %}">aceitar</a>
                                </li>
                        
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="panel-body">
                    Não há convites
                </div>    
            {% endif %}
        {% endwith %}    
    </div>    
</div>
{% endblock %}

perfis/templates/perfil.html
{% extends 'base.html' %}

{% block title %}
    {{ perfil.nome }}
{% endblock %}


{% block body %}
<div class = "col-lg-12">
		<h2 style="margin-top: 0px">{{ perfil.nome }}</h2>
		<address>			
			<a href = "mailto:{{ perfil.email }}">{{ perfil.email }}</a>
			<br>
			<strong>{{ perfil.nome_empresa }}</strong>
		
		</address>

		<a href = "{% url 'convidar' perfil.id %}">
			Convidar
		</a>
</div>		
{% endblock %}		

posts/templates/timeline.html
{% extends "base.html" %}

{% block title %}
    Linha do Tempo 
{% endblock %}


{% block body %}
    <form action="{% url 'timeline' %}" class="form-signin" method="post" >
        {% csrf_token %}
        <h3 class = "text-muted">Nova Postagem</h3>
        <textarea name="texto" class="form-control" id="exampleFormControlTextarea1" maxlength="500" 
            placeholder="Compartilhe o que você está pensando..." required></textarea>
        <button class="btn btn-lg btn-info" style="margin-top: 15px;" type="submit" value='login'>Postar</button>
    </form>
    {% for post in posts %}
    <div style="color:#777;margin-top: 20px; width: 100%;height: 100%;border: #777 1px solid; border-radius: 6px;padding: 20px;padding-top: 7px;">
        <row>
            <h4 style="color:black;"><b>{{ post.perfil.nome }}</b></h4>
            <p style="color:black;">{{post.data_postagem}}</p>
        </row>
        <row>
            <div style="width: 100%;height: 100%;">
                {{post.texto}}
            </div>
        </row>
    </div>
    {% endfor %}

{% endblock %}

usuario/templates/base_usuario.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" 
		href="{% static "styles/bootstrap.css" %}"/>
	<link rel="stylesheet" 
		href="{% static "styles/signin.css" %}"/>

</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

usuario/templates/login.html
{% extends "base_usuario.html" %}
{% block title %}
    Login 
{% endblock %}


{% block body %}
	
	<form action="{% url 'login' %}" class="form-signin" role="form" method="post">
		{% csrf_token %}
		<h2 class="form-signin-heading">Login</h2>

		<input type="text" class="form-control" id="id_username" name="username" placeholder="Nome" required autofocus>

		<input type="password" class="form-control" id="id_password" name="password" placeholder="Senha" required>

		<button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>

		<input type="hidden" name="next" value="{{ next }}">

		{% if form.errors %}
			<div class="alert alert-danger">
				<button class="close" type="button" data-dismiss="alert" aria-hidden="true">&times;</button>
				Por favor, verifique o Email e/ou Senha informados
			</div>
		{% endif %}

		<a href="{% url 'registrar' %}">registre-se</a>
	</form>

{% endblock %}

usuario/templates/registrar.html
{% extends 'base_usuario.html' %}


{% block title %}
    Registrar
{% endblock %}

{% block body %}
    <form action="{% url 'registrar' %}" class="form-signin" method="post" >
        {% csrf_token %}
        <h2 class="form-signin-heading">Registre-se</h2>
        {% if form.errors %}
            <div class='alert alert-danger'>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                {{form.non_field_errors}}
            </div>
        {% endif %}
        <input 	name="nome" id="id_nome" class="form-control" placeholder="Nome..." required autofocus>     
        <input  name="email" id="id_email" class="form-control" placeholder="Email..." required />
        <input name="senha" type="password" id="id_senha" class="form-control" placeholder="Senha..." required/>
        <hr/>
        <input name="telefone" id="id_telefone" class="form-control" placeholder="Telefone..." required/>
        <input name="nome_empresa" id="id_nome_empresa" class="form-control" placeholder="Empresa..." required/>
        <hr/>
        <button class="btn btn-lg btn-info btn-block" type="submit" value='login'>
            Registrar
        </button>
        <a href="{% url 'login' %}">já possui cadastro?</a>

    </form>
{% endblock %}